### ISSUE TITLE
Working in mess after bilingual application

### ISSUE THREAD

**Issue by eversatis** [OdooCommunityWidgets/website_multi_image#15]
After I load the second language, Chinese in my case, the module cause big mess. 
1. After saving each product's images, it would jump to the first product on the whole list in the back end.  
2. In the front end, it is kind of chaos and I do not know how to describe it. One big image in the right position, the medium images are far below. I double checked several products, it is all act the same.

Thanks for your time!

Best regards

Frank

**Comment by lukebranch** [comment]
@frankmiao2015 ,

Could you provide me with screenshots, or a temp link so that I can see what is going on?

I am running in both English and S. Chinese in my instance and I cannot reproduce the issue you have described.

This may have something to do with the fact I migrated the frontend website picture carousel from OwlCarousel to SlickCarousel recently.

If this is the issue it should be able to be resolved by clearing your browser cache and perhaps restarting Odoo. If you are behind an Nginx frontend proxy you may have some caching settings applied, in which case i'd recommend trying to access the Odoo IP+Port, rather than the Nginx proxy IP+port to see if it has something to do with the Nginx cache settings.

Please provide me with steps to reproduce if you can so that I can look into resolving the issue if it is related to the code in website_multi_image.

**Comment by eversatis** [comment]
Hi Luke,

Yes, the issue may be caused by Nginx caches. I tried in another instance and it works well. Sorry to keep the issue opens so long since I was busy with something else.

Best regards

Frank

**Comment by lukebranch** [comment]
@frankmiao2015 ,

Thanks for confirming that and no problem.
